#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.1.0pre on Mon Apr 18 17:09:54 2022
#

# This is an automatically generated file.
# Manual changes will be overwritten without warning!

import wx
import gettext
from MainDialog import MainDialog


class guinotifyApp(wx.App):
    def OnInit(self):
        self.dialog_Main = MainDialog(None, wx.ID_ANY, "")
        self.SetTopWindow(self.dialog_Main)
        print("Loading configuration...")
        self.dialog_Main.ShowModal()
        self.dialog_Main.Destroy()
        print("Saving configuration...")
        return True

# end of class guinotifyApp

if __name__ == "__main__":
    gettext.install("guinotify") # replace with the appropriate catalog name

    guinotify = guinotifyApp(0)
    guinotify.MainLoop()
