# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.1.0pre on Mon Apr 18 13:34:17 2022
#

import wx
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MenuBar(wx.MenuBar):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MenuBar.__init__
        wx.MenuBar.__init__(self, *args, **kwds)
        # end wxGlade

# end of class MenuBar
